name: TreeMauler

author: Caleb Bowen

main: treemauler.TreeMauler

commands:
    treemauler:
        description: Your description goes here
        usage: Usage of the command goes here
    treemauler_admin:
        description: Your description goes here
        usage: Usage of the command goes here

version: 0.1

